language: ruby
sudo: false
script: "script/test_all"
before_install:
  - gem install bundler
bundler_args: "--standalone --binstubs --without documentation"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.2.0
  - 2.3.0
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-9.1.13.0
  - jruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx
